In [2]:
import numpy as np 
import sys

In [9]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
a.ndim 

1

In [7]:
b.shape

(2, 3)

In [10]:
a.dtype

dtype('int16')

In [11]:
a.itemsize

2

In [14]:
a.size * a.itemsize

6

In [15]:
a.nbytes

6

In [17]:
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[1 2 3]


In [19]:
c[1,5]

13

In [22]:
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
c[:,2]

array([ 3, 10])

In [24]:
c[0,1:6:2]

array([2, 4, 6])

In [29]:
c[1,5] = 20
print(c)

c[:,2] = [1,2]
print(c)


[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [31]:
d = np.array([[[1,2], [3,4]] ,[[5,6] , [7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
d[0,1,1]

4

In [37]:
d[:,1,:] = [[9,9], [8,8]]

In [39]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.full((2,2), 99, dtype ='int16')

array([[99, 99],
       [99, 99]])

In [46]:
np.full_like(a,4)

array([4, 4, 4], dtype=int16)

In [47]:
np.full(a.shape,4)

array([4, 4, 4])

In [48]:
np.random.rand(4,2)

array([[0.50516535, 0.31443628],
       [0.62213235, 0.5724806 ],
       [0.49863312, 0.36029646],
       [0.7428039 , 0.44088207]])

In [55]:
np.random.randint(-1,7,size=(3,3))

array([[-1,  3,  3],
       [-1,  4,  0],
       [ 2,  4,  0]])

In [58]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [ ]:
d

In [63]:
output  = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [65]:
# copying caution 

In [67]:
e = np.array([1,2,3])
f = e.copy()
f[0] = 100
print(f)

[100   2   3]


In [68]:
## Math

In [69]:
g = np.array([1,2,3,4])
print(g)

[1 2 3 4]


In [70]:
g + 2

array([3, 4, 5, 6])

In [71]:
g - 2


array([-1,  0,  1,  2])

In [73]:
g * 2

array([2, 4, 6, 8])

In [74]:
g / 2

array([0.5, 1. , 1.5, 2. ])

In [75]:
g  ** 2


array([ 1,  4,  9, 16])

In [76]:
np.cos(g)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [77]:
### Linear alegbra 

In [82]:
h = np.ones((2,3))
print(h)

i = np.full((3,2) , 2)
print(i)

np.matmul(h,i)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [86]:
# Determinant
j = np.identity(3)
np.linalg.det(j)

1.0

In [87]:
#### Statistics 

In [92]:
stats = np.array([[1,2,3],[4,5,6]])
stats 

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [97]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [100]:
np.sum(stats, axis = 0)

array([5, 7, 9])

In [101]:
## Reorganising arrays

In [108]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)


after = before.reshape((4,2))
print(after)

(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [109]:
## Vertically stacking vectors 

In [111]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [112]:
## Horizontal 

In [114]:
h1 = np.ones((2,4))
h2 = np.zeros((2,4))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [115]:
## Miscellaneous

In [120]:
filedata  = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [121]:
#### Boolean Masking and advanced indexing 

In [123]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [124]:
filedata[filedata > 50 ]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [125]:
## Index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [128]:
np.all(filedata > 50, axis = 1)

array([False, False, False])

In [137]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])